theme: jekyll-theme-chirpy

lang: zh-CN
timezone: Asia/Shanghai

title: X_Y’s Blog
tagline: |-
  记录安全研究与学习复盘
  Web · Intranet · Notes
description: 记录 Web 安全、内网安全、钓鱼免杀，以及日常学习随笔。

url: "https://x-yzy.github.io"
baseurl: ""

github:
  username: X-Yzy

social:
  name: X_Y
  email: 3130796131@qq.com
  links:
    - https://github.com/X-Yzy

avatar: /assets/avatar.png
toc: true
paginate: 10

pwa:
  enabled: false
  cache:
    enabled: false

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
